name: Deploy Pipeline AWS EB

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:

    build:
      runs-on: ubuntu-20.04
      steps:
          - uses: actions/checkout@v4
            with:
             fetch-depth: 0
          - uses: actions/setup-node@v4
            with:
             cache: 'npm'
             node-version: 22
          - name: Install dependencies
            run: npm ci
          - name: Build
            run: npm run build
          - uses: actions/upload-artifact@v4
            with:
              name: dist
              path: dist


    deploy:
      needs: build
      runs-on: [ ubuntu-latest ]

      steps:
        - name: Checkout Source
          uses: actions/checkout@v4
        - name: Setup Node
          uses: actions/setup-node@v4
          with:
            cache: 'npm'
            node-version: 20
        - name: Install dependencies
          run: npm install
        - name: Download artifact dist
          uses: actions/download-artifact@v4
          with:
            name: dist

        - name: Zip application
          run: zip -r nodejs-app-build.zip .

        - name: Deploy to Elastic Beanstalk
          uses: einaregilsson/beanstalk-deploy@v21
          with:
            aws_access_key: ${{ secrets.AWS_ACCESS_KEY }}
            aws_secret_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            application_name: 'nestjs-mono-app'
            environment_name: 'Nestjs-mono-app-env'
            region: us-east-2 # O la región donde está Elastic Beanstalk
            version_label: "deploy-${{ github.run_id }}"
            deployment_package: nodejs-app-build.zip
            use_existing_version_if_available: true # es por esto o por el bucket
      